#!/bin/bash
# Auto-generated by remediationv3.py
# Resets KEEP-category rules back to FAILING state between models
# Run between models: bash break_rules.sh
echo '=== Resetting rules to failing state ==='

echo '  Breaking: sudo_custom_logfile'
sudo sed -i '/logfile/d' /etc/sudoers 2>/dev/null; sudo rm -f /etc/sudoers.d/logfile 2>/dev/null || true
echo '  Breaking: sudo_remove_no_authenticate'
echo 'Defaults !authenticate' | sudo tee /etc/sudoers.d/zz_break_authenticate > /dev/null
echo '  Breaking: sudo_require_reauthentication'
sudo rm -f /etc/sudoers.d/timeout 2>/dev/null; echo 'Defaults timestamp_timeout=15' | sudo tee /etc/sudoers.d/noauth > /dev/null
echo '  Breaking: accounts_password_pam_unix_authtok'
sudo sed -i 's/ *sha512//' /etc/pam.d/common-password 2>/dev/null || true
echo '  Breaking: accounts_passwords_pam_faillock_deny'
sudo sed -i '/faillock/d' /etc/pam.d/common-auth /etc/pam.d/common-account 2>/dev/null || true
echo '  Breaking: accounts_passwords_pam_faillock_enabled'
sudo sed -i '/pam_faillock/d' /etc/pam.d/common-auth /etc/pam.d/common-account 2>/dev/null || true
echo '  Breaking: accounts_passwords_pam_faillock_unlock_time'
sudo sed -i '/faillock/d' /etc/pam.d/common-auth 2>/dev/null || true
echo '  Breaking: accounts_password_pam_dcredit'
sudo sed -i '/dcredit/d' /etc/security/pwquality.conf 2>/dev/null || true
echo '  Breaking: accounts_password_pam_minlen'
sudo sed -i '/minlen/d' /etc/security/pwquality.conf 2>/dev/null || true
echo '  Breaking: accounts_password_pam_ucredit'
sudo sed -i '/ucredit/d' /etc/security/pwquality.conf 2>/dev/null || true
echo '  Breaking: set_password_hashing_algorithm_systemauth'
sudo sed -i 's/ *sha512//' /etc/pam.d/common-password 2>/dev/null || true
echo '  Breaking: accounts_password_pam_unix_no_remember'
sudo sed -i '/remember/d' /etc/pam.d/common-password 2>/dev/null || true
echo '  Breaking: no_empty_passwords_unix'
sudo sed -i 's/ nullok_secure//g' /etc/pam.d/common-auth 2>/dev/null || true
echo '  Breaking: accounts_umask_etc_bashrc'
sudo sed -i '/umask 027/d; /umask 077/d' /etc/bash.bashrc 2>/dev/null || true
echo '  Breaking: accounts_umask_etc_login_defs'
sudo sed -i 's/^UMASK.*/UMASK 022/' /etc/login.defs 2>/dev/null || true
echo '  Breaking: accounts_tmout'
sudo sed -i '/TMOUT/d' /etc/bash.bashrc /etc/profile /etc/profile.d/*.sh 2>/dev/null || true
echo '  Breaking: grub2_enable_apparmor'
sudo sed -i 's/ apparmor=1 security=apparmor//' /etc/default/grub 2>/dev/null; sudo update-grub 2>/dev/null || true
echo '  Breaking: sysctl_net_ipv6_conf_all_forwarding'
sudo sed -i '/net.ipv6.conf.all.forwarding/d' /etc/sysctl.conf /etc/sysctl.d/*.conf 2>/dev/null; sudo sysctl -w net.ipv6.conf.all.forwarding=1 2>/dev/null || true
echo '  Breaking: sysctl_net_ipv4_conf_all_log_martians'
sudo sed -i '/log_martians/d' /etc/sysctl.conf /etc/sysctl.d/*.conf 2>/dev/null; sudo sysctl -w net.ipv4.conf.all.log_martians=0 2>/dev/null || true
echo '  Breaking: sysctl_net_ipv4_conf_all_rp_filter'
sudo sed -i '/rp_filter/d' /etc/sysctl.conf /etc/sysctl.d/*.conf 2>/dev/null; sudo sysctl -w net.ipv4.conf.all.rp_filter=0 2>/dev/null || true
echo '  Breaking: sysctl_net_ipv4_tcp_syncookies'
sudo sed -i '/syncookies/d' /etc/sysctl.conf /etc/sysctl.d/*.conf 2>/dev/null; sudo sysctl -w net.ipv4.tcp_syncookies=0 2>/dev/null || true
echo '  Breaking: sysctl_net_ipv4_conf_all_send_redirects'
sudo sed -i '/send_redirects/d' /etc/sysctl.conf /etc/sysctl.d/*.conf 2>/dev/null; sudo sysctl -w net.ipv4.conf.all.send_redirects=1 2>/dev/null || true
echo '  Breaking: sysctl_net_ipv4_ip_forward'
sudo sed -i '/ip_forward/d' /etc/sysctl.conf /etc/sysctl.d/*.conf 2>/dev/null; sudo sysctl -w net.ipv4.ip_forward=1 2>/dev/null || true
echo '  Breaking: file_groupowner_backup_etc_gshadow'
sudo chgrp root /etc/gshadow- 2>/dev/null || true
echo '  Breaking: kernel_module_cramfs_disabled'
sudo rm -f /etc/modprobe.d/cramfs.conf 2>/dev/null || true
echo '  Breaking: kernel_module_hfs_disabled'
sudo rm -f /etc/modprobe.d/hfs.conf 2>/dev/null || true
echo '  Breaking: kernel_module_hfsplus_disabled'
sudo rm -f /etc/modprobe.d/hfsplus.conf 2>/dev/null || true
echo '  Breaking: kernel_module_jffs2_disabled'
sudo rm -f /etc/modprobe.d/jffs2.conf 2>/dev/null || true
echo '  Breaking: mount_option_dev_shm_nodev'
sudo sed -i '/\/dev\/shm/d' /etc/fstab; sudo mount -o remount /dev/shm 2>/dev/null || true
echo '  Breaking: mount_option_dev_shm_noexec'
sudo sed -i '/\/dev\/shm/d' /etc/fstab; sudo mount -o remount /dev/shm 2>/dev/null || true
echo '  Breaking: mount_option_dev_shm_nosuid'
sudo sed -i '/\/dev\/shm/d' /etc/fstab; sudo mount -o remount /dev/shm 2>/dev/null || true
echo '  Breaking: disable_users_coredumps'
sudo sed -i '/hard core/d; /soft core/d' /etc/security/limits.conf 2>/dev/null; echo '* soft core unlimited' | sudo tee -a /etc/security/limits.conf
echo '  Breaking: sysctl_fs_suid_dumpable'
sudo sed -i '/suid_dumpable/d' /etc/sysctl.conf /etc/sysctl.d/*.conf 2>/dev/null; sudo sysctl -w fs.suid_dumpable=1 2>/dev/null || true
echo '  Breaking: sysctl_kernel_randomize_va_space'
sudo sed -i '/randomize_va_space/d' /etc/sysctl.conf /etc/sysctl.d/*.conf 2>/dev/null; sudo sysctl -w kernel.randomize_va_space=0 2>/dev/null || true
echo '  Breaking: file_groupowner_cron_allow'
sudo chgrp root /etc/cron.allow 2>/dev/null || true
echo '  Breaking: file_owner_cron_allow'
sudo chown nobody:nogroup /etc/cron.allow 2>/dev/null || true
echo '  Breaking: file_permissions_cron_allow'
sudo chmod 0644 /etc/cron.allow 2>/dev/null || true
echo '  Breaking: file_permissions_cron_d'
sudo chmod 0755 /etc/cron.d 2>/dev/null || true
echo '  Breaking: file_permissions_cron_daily'
sudo chmod 0755 /etc/cron.daily 2>/dev/null || true
echo '  Breaking: file_permissions_crontab'
sudo chmod 0644 /etc/crontab 2>/dev/null || true
echo '  Breaking: package_nis_removed'
sudo apt-get install -y nis 2>/dev/null || true
echo '  Breaking: package_vsftpd_removed'
sudo apt-get install -y vsftpd 2>/dev/null || true
echo '  Breaking: service_vsftpd_disabled'
sudo systemctl enable vsftpd 2>/dev/null || true
echo '  Breaking: package_ftp_removed'
sudo apt-get install -y ftp 2>/dev/null || true
echo '  Breaking: package_tnftp_removed'
sudo apt-get install -y tnftp 2>/dev/null || true
echo '  Breaking: package_openldap-clients_removed'
sudo apt-get install -y ldap-utils 2>/dev/null || true
echo '  Breaking: package_rpcbind_removed'
sudo apt-get install -y rpcbind 2>/dev/null || true
echo '  Breaking: package_ypserv_removed'
sudo apt-get install -y nis 2>/dev/null || true
echo '  Breaking: package_telnet_removed'
sudo apt-get install -y telnet 2>/dev/null || true
echo '  Breaking: package_rsync_removed'
sudo apt-get install -y rsync 2>/dev/null || true
echo '  Breaking: service_rsyncd_disabled'
sudo systemctl enable rsync 2>/dev/null || sudo systemctl enable rsyncd 2>/dev/null || true

echo '=== Reset complete ==='
echo 'No break command for: ['aide_build_database', 'partition_for_tmp', 'grub2_uefi_password', 'service_systemd-journal-upload_enabled', 'journald_compress', 'journald_forward_to_syslog', 'journald_storage', 'systemd_journal_upload_server_tls', 'systemd_journal_upload_url', 'sysctl_net_ipv6_conf_all_accept_redirects', 'service_nftables_enabled', 'firewall_single_service_active']'
